# Dockerfile
FROM node
# or the appropriate Node version you're using

WORKDIR /app/shopping

COPY package.json .

# Install dependencies inside the container
RUN npm install

COPY . .

EXPOSE 8003

CMD ["npm", "start"]
